version: '3.8'
#volumes:
#  minio-data:
#    driver: local
#  cache:
#    driver: local
#  data-dir:
#    driver: local

services:
  app:
    build:
      context: .
    container_name: 'name-app'
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - '8080:8080'

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    command: server ~/minio --console-address :9090
    ports:
      - '9090:9090'
      - '9000:9000'
#    volumes:
#      - minio-data:/minio
  db:
    image: mysql:8
    container_name: mysql-storage-user
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=storage
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
#    volumes:
#      - data-dir:/var/lib/mysql
  redis:
    image: redis:7.4-rc-alpine
    restart: always
    container_name: redis
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass dWhjaXduZWNpbmVud25j
#    volumes:
#      - cache:/data