version: '3.8'
#volumes:
#  minio-data:
#    driver: local
#  cache:
#    driver: local
#  data-dir:
#    driver: local

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: storage
      MYSQL_USERNAME: root
#      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
#    volumes:
#      - mysql_data:/var/lib/mysql

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"

  redis:
    image: redis:7.4-rc-alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass dWhjaXduZWNpbmVud25j
#    volumes:
#      - redis_data:/data

