spring:
  profiles:
    active: prod
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mysql://localhost:3306/storage
    password: 1234
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password: dWhjaXduZWNpbmVud25j
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  flyway:
    locations: classpath:db/migration
    url: jdbc:mysql://localhost:3306/storage
    user: root
    password: 1234
    enabled: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  session:
    redis:
      namespace: "spring:session"
      flush-mode: immediate
server:
  servlet:
    session:
      timeout: 1m


logging:
  level:
    root: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs.log
    path: /

minio:
  url: http://localhost:9000
  bucket: user-files
  accessKey: eduardadministrator
  secretKey: eduardadministrator




